#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

# mangle user input
for atom in "$@"; do
	catpkg="${atom#=}"
	catpkg="${catpkg%-[0-9]*}"

	git reset HEAD ${catpkg}
	rm -rf ${catpkg}
	git checkout ${catpkg}
done
